name: Docker PR Build and Test

on:
  pull_request:
    branches: 
      - development
      - main
  push:
    branches: 
      - test-docker-workflow

jobs:
  build_and_test_docker_image:
    name: Build and Test Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t eventyay-talk:${{ github.sha }} .

  

