name: Docker PR Build and Test

on:
  pull_request:
    branches: 
      - development
      - main
  push:
    branches: 
      - test-docker-workflow

jobs:
  build_and_test_docker_image:
    name: Build and Test Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t eventyay/eventyay-talk:test .

      - name: Run tests
        run: docker run eventyay/eventyay-talk:test bash -c "pytest"
